production:
  sessions:
    default:
      database: chat_production
      hosts:
        - localhost:27017
      options:
  options:
    identity_map_enabled: true
    raise_not_found_error: false
development:
  sessions:
    default:
      database: chat_development
      hosts:
        - localhost:27017
      options:
  options:
    identity_map_enabled: true
    raise_not_found_error: false
test:
  sessions:
    default:
      database: chat_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
